name: CI Bash

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

# TODO: Mock the actual call to pushover, instead of actually doing it.

jobs:
  run_fail:
    name: Bash - Expect fail
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Script permissions
      run: chmod +x ./pushover.sh

    - name: Run script expect fail
      #continue-on-error: true
      run: |
        ./pushover.sh -v -t badtoken -u badkey -d baddevice -T Github Action Fail -m Github Action Fail || (( $? == 2 )) && exit 0 || exit $?

  run_cli:
    name: Bash - Run with Arguments
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Script permissions
      run: chmod +x ./pushover.sh

    - name: Run script with Args
      run: |
        ./pushover.sh -v -p -2 -t ${{ secrets.PUSHOVER_APP }} -u ${{ secrets.PUSHOVER_USER }} -d ${{ secrets.PUSHOVER_DEVICE }} -T Github Action Args -m Github Action Args

  run_config:
    name: Bash - Run with Config File
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Script permissions
      run: chmod +x ./pushover.sh
    
    - name: Setup Config file
      run: |
        cp ./.github/assets/pushover-config-test ./pushover-config
        sed -i "s#__PUSHOVER_USER__#${{ secrets.PUSHOVER_USER }}#g" ./pushover-config
        sed -i "s#__PUSHOVER_APP__#${{ secrets.PUSHOVER_APP }}#g" ./pushover-config
        sed -i "s#__PUSHOVER_DEVICE__#${{ secrets.PUSHOVER_DEVICE }}#g" ./pushover-config
    
    - name: Validate with config
      run: ./pushover.sh -v -x -m Github Action Config
    
    - name: Run script from config
      run: ./pushover.sh -v -m Github Action Config -p -2
