name: CI NPM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

# TODO: Mock the actual call to pushover, instead of actually doing it.

jobs:
  run_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # the Node.js versions to build on
        node: [18, 20]
    name: Node - ${{ matrix.node }}
    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    - name: NPM install
      run: npm install

    - name: Script permissions
      run: chmod +x ./pushover.sh

    - name: Setup Config file
      run: |
        cp ./.github/assets/pushover-config-test ./pushover-config
        sed -i "s#__PUSHOVER_USER__#${{ secrets.PUSHOVER_USER }}#g" ./pushover-config
        sed -i "s#__PUSHOVER_APP__#${{ secrets.PUSHOVER_APP }}#g" ./pushover-config
        sed -i "s#__PUSHOVER_DEVICE__#${{ secrets.PUSHOVER_DEVICE }}#g" ./pushover-config

    - name: Run Validate via NPM
      run:  npm run pushover-validate

    - name: Run script via NPM
      run:  npm run pushover-test

    - name: Run script with Args via NPM
      run: npm run pushover -- -p -2 -m Node Test Args ${{ matrix.node }}

    - name: Run via the bin setting
      run: npm exec pushover-bash -- -p -2 -m Node Test Args ${{ matrix.node }}
