name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    name:  Publish Package to npmjs
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: NPM install
        run: npm install

      - name: "Publish release"
        run: npm run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
